class Autogenerated {
  List<Data>? data;

  Autogenerated({this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String? name;
  String? transactionId;
  String? image;
  String? amount;
  String? status;

  Data({this.name, this.transactionId, this.image, this.amount, this.status});

  Data.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    transactionId = json['transaction_id'];
    image = json['image'];
    amount = json['amount'];
    status = json['status'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['name'] = name;
    data['transaction_id'] = transactionId;
    data['image'] = image;
    data['amount'] = amount;
    data['status'] = status;
    return data;
  }
}